# Generated by Django 4.2.4 on 2024-05-09 07:45

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_store', '0003_remove_session_show_at_session_date_session_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='price',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 9, 10, 45, 23, 281360)),
        ),
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 5, 9, 9, 0)),
        ),
    ]
