# Generated by Django 4.2.4 on 2024-05-09 09:56

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_store', '0004_session_price_alter_session_date_alter_session_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='countries',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='film',
            name='description',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='film',
            name='duration',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='uploads/film/'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 9, 12, 56, 43, 400496)),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=50, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('is_available', models.BooleanField(default=True)),
                ('seat_number', models.IntegerField()),
                ('row_number', models.CharField(max_length=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_store.session')),
            ],
        ),
    ]
